import Head from 'next/head';
import {AiOutlineDown, AiOutlineMenu} from 'react-icons/ai';
import AuthButton from '../auth/AuthButton';

const Header = () => {
  const Menu = () => (
    <div className='flex items-center justify-center'>
      <div className='mx-2'>
        <AuthButton />
      </div>
    </div>
  );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href={'/img/icon/favicon.ico'} />
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
      </Head>
      <div className='navbar bg-base-200'>
        <AiOutlineMenu />
        <div className='flex-1'>
          <a className='btn btn-ghost normal-case text-xl'>Next.js</a>
        </div>
        <Menu />
      </div>
    </div>
  );
};

export default Header;
